class Zenrows::Backends::Base
  attr_reader proxy: Zenrows::Proxy
  attr_reader config: Zenrows::Configuration
  attr_reader hooks: Zenrows::Hooks

  def initialize: (proxy: Zenrows::Proxy, config: Zenrows::Configuration, ?hooks: Zenrows::Hooks?) -> void
  def build_client: (?Hash[Symbol, untyped] options) -> untyped
  def ssl_context: () -> OpenSSL::SSL::SSLContext
  def calculate_timeouts: (?Hash[Symbol, untyped] options) -> Hash[Symbol, Integer]
  def wrap_client: (untyped client, Hash[Symbol, untyped] options) -> untyped
  def backend_name: () -> Symbol
end
