class Zenrows::ApiClient
  attr_reader api_key: String
  attr_reader api_endpoint: String
  attr_reader config: Zenrows::Configuration
  attr_reader hooks: Zenrows::Hooks

  def initialize: (?api_key: String?, ?api_endpoint: String?) ?{ (Zenrows::HookConfigurator) -> void } -> void
  def get: (String url, **untyped options) -> Zenrows::ApiResponse
  def post: (String url, ?body: String?, **untyped options) -> Zenrows::ApiResponse

  private

  def build_hooks: () { (Zenrows::HookConfigurator) -> void } -> Zenrows::Hooks
  def instrument: (Symbol method, String url, Hash[Symbol, untyped] options) { () -> untyped } -> untyped
  def build_http_client: () -> untyped
  def build_params: (String url, Hash[Symbol, untyped] options) -> Hash[Symbol, untyped]
  def handle_response: (untyped http_response, Hash[Symbol, untyped] options) -> Zenrows::ApiResponse
end
