class Zenrows::Client
  attr_reader config: Zenrows::Configuration
  attr_reader proxy: Zenrows::Proxy
  attr_reader backend: Zenrows::Backends::Base
  attr_reader hooks: Zenrows::Hooks

  def initialize: (?api_key: String?, ?host: String?, ?port: Integer?, ?backend: Symbol?) ?{ (Zenrows::HookConfigurator) -> void } -> void
  def http: (?Hash[Symbol, untyped] options) -> untyped
  def ssl_context: () -> OpenSSL::SSL::SSLContext
  def proxy_config: (?Hash[Symbol, untyped] options) -> Hash[Symbol, untyped]
  def proxy_url: (?Hash[Symbol, untyped] options) -> String
end
